//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchentsFirstProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Details
    {
        public int Order_Details_id { get; set; }
        public Nullable<int> Product_id { get; set; }
        public Nullable<int> product_Qty { get; set; }
        public Nullable<int> product_price { get; set; }
        public string Order_Id { get; set; }
        public Nullable<int> SubTotal { get; set; }
    
        public virtual Order_tbl Order_tbl { get; set; }
        public virtual Product Product { get; set; }
    }
}
