//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchentsFirstProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_tbl
    {
        public int Order_id { get; set; }
        public int Order_No { get; set; }
        public Nullable<System.DateTime> Order_Date { get; set; }
        public Nullable<int> Order_Total { get; set; }
        public Nullable<int> Register_id { get; set; }
        public Nullable<System.DateTime> Shoping_date { get; set; }
        public string Is_delivered { get; set; }
    
        public virtual Order_Details Order_Details { get; set; }
        public virtual Register Register { get; set; }
    }
}
